{{- $namespace := .Values.namespace }}
{{- $commonLabels := .Values.commonLabels }}
{{- range $name,$value :=  .Values.securedservices }}
apiVersion: v1
kind: Service
metadata:
  {{- if $value.service.annotations }}
  annotations:
{{ toYaml $value.service.annotations | indent 4 }}
{{- end }}
  labels:
{{ toYaml $commonLabels | indent 4 }}
{{ toYaml $value.componentLabels | indent 4 }}
  name: {{ $value.service.name }}
  namespace:  {{ $namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ $value.service.targetPort }}
  selector:
{{ toYaml $value.service.selector | indent 4 }}
---
{{- end}}