namespace: test-kunde

commonLabels:
  app: prometheus
  chart: prometheus-11.3.0
  release: prometheus

securedservices:
  prometheus-alertmanager:
    componentLabels:
      component: alertmanager
    service:
      name: secprometheus-alertmanager
      annotations:
      targetPort: 8001
      selector:
        app: prometheus
        component: alertmanager
        release: prometheus

  prometheus-server:
    componentLabels:
      component: server
    service:
      name: secprometheus-server
      targetPort: 8001
      selector:
        app: prometheus
        component: server
        release: prometheus


prometheus:
  serverFiles:
    prometheus.yml:
      rule_files:
       - /etc/config/recording_rules.yml
       - /etc/config/alerting_rules.yml
       - /etc/config/rules
       - /etc/config/alert-loader/*.yml
      scrape_configs:
      - job_name: kubernetes-service-endpoints
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - test-kunde
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scrape
        - action: replace
          regex: (https?)
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scheme
          target_label: __scheme__
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          source_labels:
          - __address__
          - __meta_kubernetes_service_annotation_prometheus_io_port
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_service_name
          target_label: kubernetes_name
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: kubernetes_node
      - job_name: kubernetes-service-endpoints-slow
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - test-kunde
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
        - action: replace
          regex: (https?)
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scheme
          target_label: __scheme__
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          source_labels:
          - __address__
          - __meta_kubernetes_service_annotation_prometheus_io_port
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_service_name
          target_label: kubernetes_name
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: kubernetes_node
        scrape_interval: 5m
        scrape_timeout: 30s
      - honor_labels: true
        job_name: prometheus-pushgateway
        kubernetes_sd_configs:
        - role: service
        relabel_configs:
        - action: keep
          regex: pushgateway
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_probe
      - job_name: kubernetes-services
        kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
            - test-kunde
        metrics_path: /probe
        params:
          module:
          - http_2xx
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_probe
        - source_labels:
          - __address__
          target_label: __param_target
        - replacement: blackbox
          target_label: __address__
        - source_labels:
          - __param_target
          target_label: instance
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels:
          - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - source_labels:
          - __meta_kubernetes_service_name
          target_label: kubernetes_name
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - test-kunde
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        - action: replace
          regex: (https?)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scheme
          target_label: __scheme__
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          source_labels:
          - __address__
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: kubernetes_pod_name
        - action: drop
          regex: Pending|Succeeded|Failed
          source_labels:
          - __meta_kubernetes_pod_phase
      - job_name: kubernetes-pods-slow
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - test-kunde
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
        - action: replace
          regex: (https?)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scheme
          target_label: __scheme__
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          source_labels:
          - __address__
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: kubernetes_pod_name
        - action: drop
          regex: Pending|Succeeded|Failed
          source_labels:
          - __meta_kubernetes_pod_phase
        scrape_interval: 5m
        scrape_timeout: 30s

  server:
    fullnameOverride: prometheus-server
    strategy:
      type: Recreate

    extraVolumeMounts:
      - name: alerts-volume
        mountPath: /etc/config/alert-loader
    extraVolumes:
      - name: alerts-volume
        emptyDir: {}
    sidecarContainers:
      - name: alerts-loader
        image:  kiwigrid/k8s-sidecar:0.1.20
        volumeMounts:
          - name: alerts-volume
            mountPath: /tmp
        env:
          - name: LABEL
            value: prometheusAlerts
          - name: FOLDER
            value: /tmp/
          - name: REQ_URL
            value: http://127.0.0.1:9090/-/reload
          - name: REQ_METHOD
            value: POST
          - name: NAMESPACE
            value: ALL

  alertmanager:
     fullnameOverride: prometheus-alertmanager

  kubeStateMetrics:
    fullnameOverride: prometheus-kube-state-metrics

  nodeExporter:
    fullnameOverride: prometheus-node-exporter
    extraArgs:
      collector.mountstats: ""

  pushgateway:
    fullnameOverride: prometheus-pushgateway

alert:
  name: alerts-k8s-alerts-infrastructure
  enabled: true
  files:
    infrastructure-tls.yml: |
      groups:
      - name: TLS
        rules:
        - alert: 'WARNING: Certificate is expiring'
          annotations:
            description: Certificate for {{$labels.host}} expires in {{$value}} days
            summary: 'WARNING: Certificate for {{$labels.host}} expires in {{$value}} days'
          expr: floor((nginx_ingress_controller_ssl_expire_time_seconds - time()) / (60*60*24))
            < 30
          labels:
            app: TLS
            component: infrastructure
            severity: warning
        - alert: 'CRITICAL: Certificate is expiring'
          annotations:
            description: Certificate for {{$labels.host}} expires in {{$value}} days
            summary: 'CRITICAL: Certificate for {{$labels.host}} expires in {{$value}} days'
          expr: floor((nginx_ingress_controller_ssl_expire_time_seconds - time()) / (60*60*24))
            < 7
          labels:
            app: TLS
            component: infrastructure
            severity: critical
    external_services.yml: |
      groups:
      - name: External services
        rules:
        - alert: 'CRITICAL: External services down'
          annotations:
            description: External service {{ $labels.target }} down
            summary: 'CRITICAL: External service {{ $labels.target }} - {{ $labels.instance }} down'
          expr: probe_success == 0
          for: 3m
          labels:
            app: External services
            component: infrastructure
            severity: critical