prometheus:
  alertmanagerFiles:
    alertmanager.yml:
      global:
        slack_api_url: https://hooks.slack.com/services/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
      receivers:
        - name: default
        - name: kit-slack
          slack_configs:
            - channel: '#kithosting-alerts'
              fields:
                - short: true
                  title: Cluster
                  value: KITHOSING PROD
              send_resolved: true
              text: '{{ template "slack.description" . }}'
              title: '{{ template "slack.title" . }}'
              title_link: https://kube-prometheus.vconf.dk/alerts
              username: kithosting-k8s

      route:
        group_by:
          - alertname
          - app
        group_interval: 5m
        group_wait: 30s
        receiver: default
        repeat_interval: 8h
        routes:
          - continue: true
            receiver: kit-slack
            match:
              severity: critical
      templates:
        - /etc/config/*.tmpl
    slack.tmpl: |-
      {{ define "slack.title" }}
          {{ $Alert := index .Alerts 0 }}
          {{ $Alert.Annotations.summary}}
      {{end}}
      {{ define "slack.description" }}
      {{ range .Alerts }}
      * {{ .Annotations.description }}{{ end }}
      {{end}}
