service:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: website.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - website.hosting.kitkube.dk
        secretName: website.hosting.kitkube.dk
