service:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: website.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - website.t0.hosting.kitkube.dk
        secretName: website.t0.hosting.kitkube.dk

  certificate:
    website.t0.hosting.kitkube.dk:
      namespace: test-kunde
      spec:
        secretName: website.t0.hosting.kitkube.dk
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
          group: cert-manager.io
        dnsNames:
          - website.t0.hosting.kitkube.dk
