service:
  fullnameOverride: test-website
  namespace: test-kunde

  replicaCount: 2

  image:
    repository: nginxinc/nginx-unprivileged
    tag: "alpine3.18"

  deployment:
    containerPort: 8080

    resources:
      limits:
        memory: "1024Mi"
        cpu: 1
      requests:
        memory: "512Mi"
        cpu: 500m

    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1

  service:
    port: 80
    targetPort: container-port

  netpol:
    ingress:
      ingres-nginx:
        namespaceSelector:
          kubernetes.io/metadata.name: ingress-nginx