argoApps:

  test-kunde-applications:
    test-kunde:
      path: deployment/apps
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-prod.yaml
      namespace: test-kunde

    test-website:
      path: deployment/test-website
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-prod.yaml
      namespace: test-kunde

    prometheus:
      path: deployment/prometheus
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-prod.yaml
      namespace: test-kunde
