argoApps:
  applications:
    test-kunde-applications:
      path: apps
      targetRevision: prod
      valueFiles:
        - values.yaml
        - values-prod.yaml
      sync: 
        auto: true

    test-website:
      path: test-website
      targetRevision: prod
      valueFiles:
        - values.yaml
        - values-prod.yaml
      sync: 
        auto: true
