argoApps:
  applications:
    test-kunde-applications:
      path: apps
      targetRevision: prod
      valueFiles:
        - values.yaml
        - values-prod.yaml
      namespace: test-kunde

    test-website:
      path: test-website
      targetRevision: prod
      valueFiles:
        - values.yaml
        - values-prod.yaml
      namespace: test-kunde
