argoApps:
  server: https://kubernetes.default.svc
  repoUrl: git@github.com:KvalitetsIT/kithosting-tenant-applications.git

  namespaceArgo: infrastructure
  namespace: test-kunde
  project: test-kunde
