argoApps:
  server: https://kubernetes.default.svc
  repoUrl: https://github.com/KvalitetsIT/kithosting-test-kunde.git

  namespace: test-kunde
  project: test-kunde

  projects:
    test-kunde:
      description: Test Kunde
      sources:
        - https://github.com/KvalitetsIT/kithosting-test-kunde.git
      destinations:
        - namespace: test-kunde
          server: https://kubernetes.default.svc
      ignored:
        - Secret
        - Role
        - RoleBinding
      warnignored: true
