argoApps:
  applications:
    test-kunde-applications:
      path: apps
      targetRevision: test
      valueFiles:
        - values.yaml
        - values-test.yaml

    test-website:
      path: test-website
      targetRevision: test
      valueFiles:
        - values.yaml
        - values-test.yaml
